version: '3'
services:
  spark:
    image: jupyter/all-spark-notebook
    container_name: spark-api-to-s3
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work/notebooks/
      - ../spark:/home/jovyan/scripts/